// inheritance rules data
const INHtypes = [
	{'INHtype': 'SlashType',	'Slash': true, 'Strike': true, 'Pierce': true, 'Fire': false, 'Ice': false, 'Elec': false, 'Wind': false, 'Light': false, 'Dark': false, 'Recovery': true, 'Enhance': true, 'Status': false, 'Special': true, 'Almighty': true, 'Passive': true},
	{'INHtype': 'StrikeType',	'Slash': true, 'Strike': true, 'Pierce': true, 'Fire': false, 'Ice': false, 'Elec': false, 'Wind': false, 'Light': false, 'Dark': false, 'Recovery': true, 'Enhance': true, 'Status': false, 'Special': true, 'Almighty': true, 'Passive': true},
	{'INHtype': 'PierceType',	'Slash': true, 'Strike': true, 'Pierce': true, 'Fire': false, 'Ice': false, 'Elec': false, 'Wind': false, 'Light': false, 'Dark': false, 'Recovery': true, 'Enhance': true, 'Status': false, 'Special': true, 'Almighty': true, 'Passive': true},
	{'INHtype': 'FireType',		'Slash': true, 'Strike': true, 'Pierce': true, 'Fire': true, 'Ice': false, 'Elec': false, 'Wind': false, 'Light': true, 'Dark': true, 'Recovery': true, 'Enhance': true, 'Status': true, 'Special': true, 'Almighty': true, 'Passive': true},
	{'INHtype': 'IceType',		'Slash': true, 'Strike': true, 'Pierce': true, 'Fire': false, 'Ice': true, 'Elec': false, 'Wind': false, 'Light': true, 'Dark': true, 'Recovery': true, 'Enhance': true, 'Status': true, 'Special': true, 'Almighty': true, 'Passive': true},
	{'INHtype': 'ElecType',		'Slash': true, 'Strike': true, 'Pierce': true, 'Fire': false, 'Ice': false, 'Elec': true, 'Wind': false, 'Light': true, 'Dark': true, 'Recovery': true, 'Enhance': true, 'Status': true, 'Special': true, 'Almighty': true, 'Passive': true},
	{'INHtype': 'WindType',		'Slash': true, 'Strike': true, 'Pierce': true, 'Fire': false, 'Ice': false, 'Elec': false, 'Wind': true, 'Light': true, 'Dark': true, 'Recovery': true, 'Enhance': true, 'Status': true, 'Special': true, 'Almighty': true, 'Passive': true},
	{'INHtype': 'LightType',	'Slash': false, 'Strike': false, 'Pierce': false, 'Fire': true, 'Ice': true, 'Elec': true, 'Wind': true, 'Light': true, 'Dark': false, 'Recovery': true, 'Enhance': true, 'Status': false, 'Special': true, 'Almighty': true, 'Passive': true},
	{'INHtype': 'DarkType',		'Slash': true, 'Strike': true, 'Pierce': true, 'Fire': true, 'Ice': true, 'Elec': true, 'Wind': true, 'Light': false, 'Dark': true, 'Recovery': false, 'Enhance': false, 'Status': true, 'Special': true, 'Almighty': true, 'Passive': true},
	{'INHtype': 'DualLDType',	'Slash': false, 'Strike': false, 'Pierce': false, 'Fire': true, 'Ice': true, 'Elec': true, 'Wind': true, 'Light': true, 'Dark': true, 'Recovery': true, 'Enhance': true, 'Status': true, 'Special': true, 'Almighty': true, 'Passive': true},
	{'INHtype': 'RecoveryType',	'Slash': false, 'Strike': false, 'Pierce': false, 'Fire': true, 'Ice': true, 'Elec': true, 'Wind': true, 'Light': true, 'Dark': true, 'Recovery': true, 'Enhance': true, 'Status': true, 'Special': true, 'Almighty': true, 'Passive': true},
	{'INHtype': 'StatusType',	'Slash': false, 'Strike': false, 'Pierce': false, 'Fire': true, 'Ice': true, 'Elec': true, 'Wind': true, 'Light': false, 'Dark': true, 'Recovery': false, 'Enhance': true, 'Status': true, 'Special': true, 'Almighty': true, 'Passive': true},
	{'INHtype': 'AllType',		'Slash': true, 'Strike': true, 'Pierce': true, 'Fire': true, 'Ice': true, 'Elec': true, 'Wind': true, 'Light': true, 'Dark': true, 'Recovery': true, 'Enhance': true, 'Status': true, 'Special': true, 'Almighty': true, 'Passive': true},
];

// persona list with inherit types

const personae = [
	{'name': 'Abaddon', 'INHtype': 'StatusType'},
	{'name': 'Alice', 'INHtype': 'DarkType'},
	{'name': 'Alilat', 'INHtype': 'RecoveryType'},
	{'name': 'Alp', 'INHtype': 'RecoveryType'},
	{'name': 'Ananta', 'INHtype': 'RecoveryType'},
	{'name': 'Angel', 'INHtype': 'WindType'},
	{'name': 'Anubis', 'INHtype': 'DualLDType'},
	{'name': 'Apsaras', 'INHtype': 'IceType'},
	{'name': 'Ara Mitama', 'INHtype': 'StrikeType'},
	{'name': 'Arahabaki', 'INHtype': 'StatusType'},
	{'name': 'Archangel', 'INHtype': 'LightType'},
	{'name': 'Ares', 'INHtype': 'SlashType'},
	{'name': 'Asura', 'INHtype': 'FireType'},
	{'name': 'Atropos', 'INHtype': 'WindType'},
	{'name': 'Attis', 'INHtype': 'RecoveryType'},
	{'name': 'Barong', 'INHtype': 'SlashType'},
	{'name': 'Beelzebub', 'INHtype': 'StatusType'},
	{'name': 'Berith', 'INHtype': 'FireType'},
	{'name': 'Bishamonten', 'INHtype': 'FireType'},
	{'name': 'Black Frost', 'INHtype': 'AllType'},
	{'name': 'Byakko', 'INHtype': 'SlashType'},
	{'name': 'Chernobog', 'INHtype': 'SlashType'},
	{'name': 'Chi You', 'INHtype': 'PierceType'},
	{'name': 'Chimera', 'INHtype': 'SlashType'},
	{'name': 'Clotho', 'INHtype': 'WindType'},
	{'name': 'Cu Chulainn', 'INHtype': 'PierceType'},
	{'name': 'Cybele', 'INHtype': 'RecoveryType'},
	{'name': 'Daisoujou', 'INHtype': 'LightType'},
	{'name': 'Decarabia', 'INHtype': 'AllType'},
	{'name': 'Dionysus', 'INHtype': 'ElecType'},
	{'name': 'Dominion', 'INHtype': 'LightType'},
	{'name': 'Eligor', 'INHtype': 'PierceType'},
	{'name': 'Flauros', 'INHtype': 'FireType'},
	{'name': 'Forneus', 'INHtype': 'IceType'},
	{'name': 'Fortuna', 'INHtype': 'WindType'},
	{'name': 'Gabriel', 'INHtype': 'IceType'},
	{'name': 'Ganesha', 'INHtype': 'SlashType'},
	{'name': 'Ganga', 'INHtype': 'IceType'},
	{'name': 'Garuda', 'INHtype': 'WindType'},
	{'name': 'Genbu', 'INHtype': 'IceType'},
	{'name': 'Girimekhala', 'INHtype': 'SlashType'},
	{'name': 'Gurr', 'INHtype': 'SlashType'},
	{'name': 'Hanuman', 'INHtype': 'SlashType'},
	{'name': 'Hariti', 'INHtype': 'RecoveryType'},
	{'name': 'Hokuto Seikun', 'INHtype': 'ElecType'},
	{'name': 'Horus', 'INHtype': 'LightType'},
	{'name': 'Incubus', 'INHtype': 'StatusType'},
	{'name': 'Inugami', 'INHtype': 'StatusType'},
	{'name': 'Jack Frost', 'INHtype': 'IceType'},
	{'name': 'Jatayu', 'INHtype': 'WindType'},
	{'name': 'Jikokuten', 'INHtype': 'SlashType'},
	{'name': 'Kaiwan', 'INHtype': 'StatusType'},
	{'name': 'Kali', 'INHtype': 'SlashType'},
	{'name': 'Kikuri-Hime', 'INHtype': 'RecoveryType'},
	{'name': 'King Frost', 'INHtype': 'IceType'},
	{'name': 'Kingu', 'INHtype': 'RecoveryType'},
	{'name': 'Kohryu', 'INHtype': 'RecoveryType'},
	{'name': 'Koumokuten', 'INHtype': 'StrikeType'},
	{'name': 'Kurama Tengu', 'INHtype': 'StatusType'},
	{'name': 'Kusi Mitama', 'INHtype': 'WindType'},
	{'name': 'Lachesis', 'INHtype': 'WindType'},
	{'name': 'Laksmi', 'INHtype': 'IceType'},
	{'name': 'Lamia', 'INHtype': 'DarkType'},
	{'name': 'Leanan Sidhe', 'INHtype': 'RecoveryType'},
	{'name': 'Legion', 'INHtype': 'AllType'},
	{'name': 'Lilim', 'INHtype': 'StatusType'},
	{'name': 'Lilith', 'INHtype': 'StatusType'},
	{'name': 'Loa', 'INHtype': 'DarkType'},
	{'name': 'Loki', 'INHtype': 'AllType'},
	{'name': 'Lucifer', 'INHtype': 'StrikeType'},
	{'name': 'Masakado', 'INHtype': 'DarkType'},
	{'name': 'Melchizedek', 'INHtype': 'LightType'},
	{'name': 'Messiah', 'INHtype': 'DualLDType'},
	{'name': 'Metatron', 'INHtype': 'LightType'},
	{'name': 'Michael', 'INHtype': 'ElecType'},
	{'name': 'Mithra', 'INHtype': 'LightType'},
	{'name': 'Mokoi', 'INHtype': 'StatusType'},
	{'name': 'Mot', 'INHtype': 'DarkType'},
	{'name': 'Mother Harlot', 'INHtype': 'DarkType'},
	{'name': 'Mothman', 'INHtype': 'StatusType'},
	{'name': 'Naga', 'INHtype': 'PierceType'},
	{'name': 'Nandi', 'INHtype': 'WindType'},
	{'name': 'Narasimha', 'INHtype': 'SlashType'},
	{'name': 'Narcissus', 'INHtype': 'StatusType'},
	{'name': 'Nata Taishi', 'INHtype': 'StrikeType'},
	{'name': 'Nebiros', 'INHtype': 'StatusType'},
	{'name': 'Nekomata', 'INHtype': 'FireType'},
	{'name': 'Nigi Mitama', 'INHtype': 'WindType'},
	{'name': 'Norn', 'INHtype': 'WindType'},
	{'name': 'Oberon', 'INHtype': 'ElecType'},
	{'name': 'odin', 'INHtype': 'ElecType'},
	{'name': 'Okuninushi', 'INHtype': 'FireType'},
	{'name': 'Omoikane', 'INHtype': 'ElecType'},
	{'name': 'Orobas', 'INHtype': 'WindType'},
	{'name': 'Orpheus', 'INHtype': 'FireType'},
	{'name': 'Orthrus', 'INHtype': 'FireType'},
	{'name': 'Ose', 'INHtype': 'AllType'},
	{'name': 'oumitsunu', 'INHtype': 'StrikeType'},
	{'name': 'Pale Rider', 'INHtype': 'DarkType'},
	{'name': 'Pazuzu', 'INHtype': 'StatusType'},
	{'name': 'Pixie', 'INHtype': 'RecoveryType'},
	{'name': 'Power', 'INHtype': 'LightType'},
	{'name': 'Principality', 'INHtype': 'LightType'},
	{'name': 'Pyro Jack', 'INHtype': 'FireType'},
	{'name': 'Queen Mab', 'INHtype': 'RecoveryType'},
	{'name': 'Quetzalcoatl', 'INHtype': 'WindType'},
	{'name': 'Raja Naga', 'INHtype': 'PierceType'},
	{'name': 'Rangda', 'INHtype': 'FireType'},
	{'name': 'Raphael', 'INHtype': 'SlashType'},
	{'name': 'Saki Mitama', 'INHtype': 'RecoveryType'},
	{'name': 'Samael', 'INHtype': 'DarkType'},
	{'name': 'Sandalphon', 'INHtype': 'LightType'},
	{'name': 'Sarasvati', 'INHtype': 'IceType'},
	{'name': 'Satan', 'INHtype': 'DualLDType'},
	{'name': 'Sati', 'INHtype': 'FireType'},
	{'name': 'Saturnus', 'INHtype': 'FireType'},
	{'name': 'Scathach', 'INHtype': 'PierceType'},
	{'name': 'Seiryuu', 'INHtype': 'IceType'},
	{'name': 'Seiten Taisei', 'INHtype': 'PierceType'},
	{'name': 'Seth', 'INHtype': 'FireType'},
	{'name': 'Shiva', 'INHtype': 'ElecType'},
	{'name': 'Siegfried', 'INHtype': 'SlashType'},
	{'name': 'Skadi', 'INHtype': 'IceType'},
	{'name': 'Succubus', 'INHtype': 'StatusType'},
	{'name': 'Surt', 'INHtype': 'FireType'},
	{'name': 'Susano-o', 'INHtype': 'AllType'},
	{'name': 'Suzaku', 'INHtype': 'ElecType'},
	{'name': 'Take-mikazuchi', 'INHtype': 'ElecType'},
	{'name': 'Take-minakata', 'INHtype': 'ElecType'},
	{'name': 'Taraka', 'INHtype': 'SlashType'},
	{'name': 'Thanatos', 'INHtype': 'DarkType'},
	{'name': 'Thor', 'INHtype': 'ElecType'},
	{'name': 'Throne', 'INHtype': 'LightType'},
	{'name': 'Titan', 'INHtype': 'SlashType'},
	{'name': 'Titania', 'INHtype': 'RecoveryType'},
	{'name': 'Trumpeter', 'INHtype': 'DualLDType'},
	{'name': 'Ubelluris', 'INHtype': 'StrikeType'},
	{'name': 'Unicorn', 'INHtype': 'RecoveryType'},
	{'name': 'Uriel', 'INHtype': 'LightType'},
	{'name': 'Valkyrie', 'INHtype': 'SlashType'},
	{'name': 'Vasuki', 'INHtype': 'LightType'},
	{'name': 'Vetala', 'INHtype': 'StatusType'},
	{'name': 'Virtue', 'INHtype': 'LightType'},
	{'name': 'Vishnu', 'INHtype': 'StrikeType'},
	{'name': 'Yamatano-orochi', 'INHtype': 'StrikeType'},
	{'name': 'Yatagarasu', 'INHtype': 'RecoveryType'},
	{'name': 'Yomotsu Shikome', 'INHtype': 'DarkType'},
	{'name': 'Zouchouten', 'INHtype': 'StrikeType'},
];

// skill list with inherit types

const skills = [
	{'skname': 'Cleave', 'sktype': 'Slash' },
	{'skname': 'Power Slash', 'sktype': 'Slash' },
	{'skname': 'Zan-ei', 'sktype': 'Slash' },
	{'skname': 'Getsu-ei', 'sktype': 'Slash' },
	{'skname': 'Gale Slash', 'sktype': 'Slash' },
	{'skname': 'Mighty Swing', 'sktype': 'Slash' },
	{'skname': 'Fatal End', 'sktype': 'Slash' },
	{'skname': 'Blade of Fury', 'sktype': 'Slash' },
	{'skname': 'Deathbound', 'sktype': 'Slash' },
	{'skname': 'Tempest Slash', 'sktype': 'Slash' },
	{'skname': 'Heavens Blade', 'sktype': 'Slash' },
	{'skname': 'Brave Blade', 'sktype': 'Slash' },
	{'skname': 'Vorpal Blade', 'sktype': 'Slash' },
	{'skname': 'Bash', 'sktype': 'Strike' },
	{'skname': 'Sonic Punch', 'sktype': 'Strike' },
	{'skname': 'Assault Dive', 'sktype': 'Strike' },
	{'skname': 'Kill Rush', 'sktype': 'Strike' },
	{'skname': 'Swift Strike', 'sktype': 'Strike' },
	{'skname': 'Herculean Strike', 'sktype': 'Strike' },
	{'skname': 'Gigantic Fist', 'sktype': 'Strike' },
	{'skname': 'Heat Wave', 'sktype': 'Strike' },
	{'skname': 'Vicious Strike', 'sktype': 'Strike' },
	{'skname': 'Weary Thrust', 'sktype': 'Strike' },
	{'skname': 'Akasha Arts', 'sktype': 'Strike' },
	{'skname': 'Gods Hand', 'sktype': 'Strike' },
	{'skname': 'Single Shot', 'sktype': 'Pierce' },
	{'skname': 'Double Fangs', 'sktype': 'Pierce' },
	{'skname': 'Holy Arrow', 'sktype': 'Pierce' },
	{'skname': 'Twin Shot', 'sktype': 'Pierce' },
	{'skname': 'Torrent Shot', 'sktype': 'Pierce' },
	{'skname': 'Cruel Attack', 'sktype': 'Pierce' },
	{'skname': 'Poison Arrow', 'sktype': 'Pierce' },
	{'skname': 'Vile Assault', 'sktype': 'Pierce' },
	{'skname': 'Arrow Rain', 'sktype': 'Pierce' },
	{'skname': 'Myriad Arrows', 'sktype': 'Pierce' },
	{'skname': 'Primal Force', 'sktype': 'Pierce' },
	{'skname': 'Pralaya', 'sktype': 'Pierce' },
	{'skname': 'Agi', 'sktype': 'Fire' },
	{'skname': 'Maragi', 'sktype': 'Fire' },
	{'skname': 'Agilao', 'sktype': 'Fire' },
	{'skname': 'Maragion', 'sktype': 'Fire' },
	{'skname': 'Agidyne', 'sktype': 'Fire' },
	{'skname': 'Maragidyne', 'sktype': 'Fire' },
	{'skname': 'Ragnarok', 'sktype': 'Fire' },
	{'skname': 'Maralagidyne', 'sktype': 'Fire' },
	{'skname': 'Bufu', 'sktype': 'Ice' },
	{'skname': 'Mabufu', 'sktype': 'Ice' },
	{'skname': 'Bufula', 'sktype': 'Ice' },
	{'skname': 'Mabufula', 'sktype': 'Ice' },
	{'skname': 'Bufudyne', 'sktype': 'Ice' },
	{'skname': 'Mabufudyne', 'sktype': 'Ice' },
	{'skname': 'Niflheim', 'sktype': 'Ice' },
	{'skname': 'Zio', 'sktype': 'Elec' },
	{'skname': 'Mazio', 'sktype': 'Elec' },
	{'skname': 'Zionga', 'sktype': 'Elec' },
	{'skname': 'Mazionga', 'sktype': 'Elec' },
	{'skname': 'Ziodyne', 'sktype': 'Elec' },
	{'skname': 'Maziodyne', 'sktype': 'Elec' },
	{'skname': 'Thunder Reign', 'sktype': 'Elec' },
	{'skname': 'Garu', 'sktype': 'Wind' },
	{'skname': 'Magaru', 'sktype': 'Wind' },
	{'skname': 'Garula', 'sktype': 'Wind' },
	{'skname': 'Magarula', 'sktype': 'Wind' },
	{'skname': 'Garudyne', 'sktype': 'Wind' },
	{'skname': 'Magarudyne', 'sktype': 'Wind' },
	{'skname': 'Panta Rhei', 'sktype': 'Wind' },
	{'skname': 'Hama', 'sktype': 'Light' },
	{'skname': 'Mahama', 'sktype': 'Light' },
	{'skname': 'Hamaon', 'sktype': 'Light' },
	{'skname': 'Mahamaon', 'sktype': 'Light' },
	{'skname': 'Samsara', 'sktype': 'Light' },
	{'skname': 'Mudo', 'sktype': 'Dark' },
	{'skname': 'Mamudo', 'sktype': 'Dark' },
	{'skname': 'Mudoon', 'sktype': 'Dark' },
	{'skname': 'Mamudoon', 'sktype': 'Dark' },
	{'skname': 'Die for Me!', 'sktype': 'Dark' },
	{'skname': 'Dia', 'sktype': 'Recover' },
	{'skname': 'Media', 'sktype': 'Recover' },
	{'skname': 'Diarama', 'sktype': 'Recover' },
	{'skname': 'Mediarama', 'sktype': 'Recover' },
	{'skname': 'Diarahan', 'sktype': 'Recover' },
	{'skname': 'Mediarahan', 'sktype': 'Recover' },
	{'skname': 'Salvation', 'sktype': 'Recover' },
	{'skname': 'Recarm', 'sktype': 'Recover' },
	{'skname': 'Samarecarm', 'sktype': 'Recover' },
	{'skname': 'Patra', 'sktype': 'Recover' },
	{'skname': 'Re Patra', 'sktype': 'Recover' },
	{'skname': 'Posumudi', 'sktype': 'Recover' },
	{'skname': 'Charmdi', 'sktype': 'Recover' },
	{'skname': 'Enradi', 'sktype': 'Recover' },
	{'skname': 'Me Patra', 'sktype': 'Recover' },
	{'skname': 'Amrita', 'sktype': 'Recover' },
	{'skname': 'Tarukaja', 'sktype': 'Enhance' },
	{'skname': 'Tarunda', 'sktype': 'Enhance' },
	{'skname': 'Matarukaja', 'sktype': 'Enhance' },
	{'skname': 'Matarunda', 'sktype': 'Enhance' },
	{'skname': 'Rakukaja', 'sktype': 'Enhance' },
	{'skname': 'Rakunda', 'sktype': 'Enhance' },
	{'skname': 'Marakukaja', 'sktype': 'Enhance' },
	{'skname': 'Marakunda', 'sktype': 'Enhance' },
	{'skname': 'Sukukaja', 'sktype': 'Enhance' },
	{'skname': 'Sukunda', 'sktype': 'Enhance' },
	{'skname': 'Masukukaja', 'sktype': 'Enhance' },
	{'skname': 'Masukunda', 'sktype': 'Enhance' },
	{'skname': 'Dekunda', 'sktype': 'Enhance' },
	{'skname': 'Dekaja', 'sktype': 'Enhance' },
	{'skname': 'Rebellion', 'sktype': 'Enhance' },
	{'skname': 'Revolution', 'sktype': 'Enhance' },
	{'skname': 'Power Charge', 'sktype': 'Enhance' },
	{'skname': 'Mind Charge', 'sktype': 'Enhance' },
	{'skname': 'Fire Break', 'sktype': 'Enhance' },
	{'skname': 'Ice Break', 'sktype': 'Enhance' },
	{'skname': 'Elec Break', 'sktype': 'Enhance' },
	{'skname': 'Wind Break', 'sktype': 'Enhance' },
	{'skname': 'Tetrakarn', 'sktype': 'Enhance' },
	{'skname': 'Makarakarn', 'sktype': 'Enhance' },
	{'skname': 'Evil Touch', 'sktype': 'Status' },
	{'skname': 'Evil Smile?', 'sktype': 'Status' },
	{'skname': 'Ghastly Wail', 'sktype': 'Status' },
	{'skname': 'Pulinpa', 'sktype': 'Status' },
	{'skname': 'Tentarafoo?', 'sktype': 'Status' },
	{'skname': 'Bewilder', 'sktype': 'Status' },
	{'skname': 'Eerie Sound?', 'sktype': 'Status' },
	{'skname': 'Poisma', 'sktype': 'Status' },
	{'skname': 'Poison Mist', 'sktype': 'Status' },
	{'skname': 'Virus Breath', 'sktype': 'Status' },
	{'skname': 'Marin Karin', 'sktype': 'Status' },
	{'skname': 'Sexy Dance', 'sktype': 'Status' },
	{'skname': 'Provoke', 'sktype': 'Status' },
	{'skname': 'Infuriate', 'sktype': 'Status' },
	{'skname': 'Recarmdra', 'sktype': 'Special' },
	{'skname': 'Trafuri', 'sktype': 'Special' },
	{'skname': 'Life Drain', 'sktype': 'Almight' },
	{'skname': 'Spirit Drain', 'sktype': 'Almight' },
	{'skname': 'Foul Breath', 'sktype': 'Almight' },
	{'skname': 'Stagnant Air', 'sktype': 'Almight' },
	{'skname': 'Megido', 'sktype': 'Almight' },
	{'skname': 'Megidola', 'sktype': 'Almight' },
	{'skname': 'Megidolaon?', 'sktype': 'Almight' },
	{'skname': 'Black Viper', 'sktype': 'Almight' },
	{'skname': 'Morning Star', 'sktype': 'Almight' },
	{'skname': 'Dodge Slash', 'sktype': 'Passive' },
	{'skname': 'Evade Slash', 'sktype': 'Passive' },
	{'skname': 'Resist Slash', 'sktype': 'Passive' },
	{'skname': 'Null Slash', 'sktype': 'Passive' },
	{'skname': 'Repel Slash', 'sktype': 'Passive' },
	{'skname': 'Absorb Slash', 'sktype': 'Passive' },
	{'skname': 'Dodge Strike', 'sktype': 'Passive' },
	{'skname': 'Evade Strike', 'sktype': 'Passive' },
	{'skname': 'Resist Strike', 'sktype': 'Passive' },
	{'skname': 'Null Strike', 'sktype': 'Passive' },
	{'skname': 'Repel Strike', 'sktype': 'Passive' },
	{'skname': 'Absorb Strike', 'sktype': 'Passive' },
	{'skname': 'Dodge Pierce', 'sktype': 'Passive' },
	{'skname': 'Evade Pierce', 'sktype': 'Passive' },
	{'skname': 'Resist Pierce', 'sktype': 'Passive' },
	{'skname': 'Null Pierce', 'sktype': 'Passive' },
	{'skname': 'Repel Pierce', 'sktype': 'Passive' },
	{'skname': 'Absorb Pierce', 'sktype': 'Passive' },
	{'skname': 'Dodge Fire', 'sktype': 'Passive' },
	{'skname': 'Evade Fire', 'sktype': 'Passive' },
	{'skname': 'Resist Fire', 'sktype': 'Passive' },
	{'skname': 'Null Fire', 'sktype': 'Passive' },
	{'skname': 'Repel Fire', 'sktype': 'Passive' },
	{'skname': 'Absorb Fire', 'sktype': 'Passive' },
	{'skname': 'Dodge Ice', 'sktype': 'Passive' },
	{'skname': 'Evade Ice', 'sktype': 'Passive' },
	{'skname': 'Resist Ice', 'sktype': 'Passive' },
	{'skname': 'Null Ice', 'sktype': 'Passive' },
	{'skname': 'Repel Ice', 'sktype': 'Passive' },
	{'skname': 'Absorb Ice', 'sktype': 'Passive' },
	{'skname': 'Dodge Elec', 'sktype': 'Passive' },
	{'skname': 'Evade Elec', 'sktype': 'Passive' },
	{'skname': 'Resist Elec', 'sktype': 'Passive' },
	{'skname': 'Null Elec', 'sktype': 'Passive' },
	{'skname': 'Repel Elec', 'sktype': 'Passive' },
	{'skname': 'Absorb Elec', 'sktype': 'Passive' },
	{'skname': 'Dodge Wind', 'sktype': 'Passive' },
	{'skname': 'Evade Wind', 'sktype': 'Passive' },
	{'skname': 'Resist Wind', 'sktype': 'Passive' },
	{'skname': 'Null Wind', 'sktype': 'Passive' },
	{'skname': 'Repel Wind', 'sktype': 'Passive' },
	{'skname': 'Absorb Wind', 'sktype': 'Passive' },
	{'skname': 'Survive Light', 'sktype': 'Passive' },
	{'skname': 'Endure Light', 'sktype': 'Passive' },
	{'skname': 'Resist Light', 'sktype': 'Passive' },
	{'skname': 'Null Light', 'sktype': 'Passive' },
	{'skname': 'Repel Light', 'sktype': 'Passive' },
	{'skname': 'Survive Dark', 'sktype': 'Passive' },
	{'skname': 'Endure Dark', 'sktype': 'Passive' },
	{'skname': 'Resist Dark', 'sktype': 'Passive' },
	{'skname': 'Null Dark', 'sktype': 'Passive' },
	{'skname': 'Repel Dark', 'sktype': 'Passive' },
	{'skname': 'Fire Boost', 'sktype': 'Passive' },
	{'skname': 'Fire Amp', 'sktype': 'Passive' },
	{'skname': 'Ice Boost', 'sktype': 'Passive' },
	{'skname': 'Ice Amp', 'sktype': 'Passive' },
	{'skname': 'Elec Boost', 'sktype': 'Passive' },
	{'skname': 'Elec Amp', 'sktype': 'Passive' },
	{'skname': 'Wind Boost', 'sktype': 'Passive' },
	{'skname': 'Wind Amp', 'sktype': 'Passive' },
	{'skname': 'Hama Boost', 'sktype': 'Passive' },
	{'skname': 'Mudo Boost', 'sktype': 'Passive' },
	{'skname': 'Fear Boost', 'sktype': 'Passive' },
	{'skname': 'Panic Boost', 'sktype': 'Passive' },
	{'skname': 'Distress Boost', 'sktype': 'Passive' },
	{'skname': 'Poison Boost', 'sktype': 'Passive' },
	{'skname': 'Charm Boost', 'sktype': 'Passive' },
	{'skname': 'Rage Boost', 'sktype': 'Passive' },
	{'skname': 'Ailment Boost', 'sktype': 'Passive' },
	{'skname': 'Null Fear', 'sktype': 'Passive' },
	{'skname': 'Null Panic', 'sktype': 'Passive' },
	{'skname': 'Null Distress', 'sktype': 'Passive' },
	{'skname': 'Null Poison', 'sktype': 'Passive' },
	{'skname': 'Null Charm', 'sktype': 'Passive' },
	{'skname': 'Null Rage', 'sktype': 'Passive' },
	{'skname': 'Null Shock', 'sktype': 'Passive' },
	{'skname': 'Null Freeze', 'sktype': 'Passive' },
	{'skname': 'Auto-Tarukaja', 'sktype': 'Passive' },
	{'skname': 'Auto-Rakukaja', 'sktype': 'Passive' },
	{'skname': 'Auto-Sukukaja', 'sktype': 'Passive' },
	{'skname': 'Auto-Mataru?', 'sktype': 'Passive' },
	{'skname': 'Auto-Maraku', 'sktype': 'Passive' },
	{'skname': 'Auto-Masuku', 'sktype': 'Passive' },
	{'skname': 'Divine Grace', 'sktype': 'Passive' },
	{'skname': 'Regenerate 1', 'sktype': 'Passive' },
	{'skname': 'Regenerate 2?', 'sktype': 'Passive' },
	{'skname': 'Regenerate 3', 'sktype': 'Passive' },
	{'skname': 'Spring of Life', 'sktype': 'Passive' },
	{'skname': 'Invigorate 1', 'sktype': 'Passive' },
	{'skname': 'Invigorate 2', 'sktype': 'Passive' },
	{'skname': 'Invigorate 3', 'sktype': 'Passive' },
	{'skname': 'Cool Breeze', 'sktype': 'Passive' },
	{'skname': 'Victory Cry', 'sktype': 'Passive' },
	{'skname': 'Growth 1', 'sktype': 'Passive' },
	{'skname': 'Growth 2', 'sktype': 'Passive' },
	{'skname': 'Growth 3', 'sktype': 'Passive' },
	{'skname': 'Endure', 'sktype': 'Passive' },
	{'skname': 'Enduring Soul', 'sktype': 'Passive' },
	{'skname': 'Counter', 'sktype': 'Passive' },
	{'skname': 'Counterstrike', 'sktype': 'Passive' },
	{'skname': 'High Counter', 'sktype': 'Passive' },
	{'skname': 'Alertness', 'sktype': 'Passive' },
	{'skname': 'Fast Retreat', 'sktype': 'Passive' },
	{'skname': 'Apt Pupil', 'sktype': 'Passive' },
	{'skname': 'Sharp Student', 'sktype': 'Passive' },
	{'skname': 'Raging Tiger', 'sktype': 'Passive' },
	{'skname': '1hSwd Master', 'sktype': 'Passive' },
	{'skname': '2hSwd Master', 'sktype': 'Passive' },
	{'skname': 'Fist Master', 'sktype': 'Passive' },
	{'skname': 'Heavy Master', 'sktype': 'Passive' },
	{'skname': 'Spear Master', 'sktype': 'Passive' },
	{'skname': 'Bow Master', 'sktype': 'Passive' },
	{'skname': 'Weapons Master', 'sktype': 'Passive' },
	{'skname': 'Goddess Knowledge', 'sktype': 'Passive' },
	{'skname': 'Arms Master', 'sktype': 'Passive' },
	{'skname': 'Spell Master', 'sktype': 'Passive' },
	{'skname': 'Unshaken Will', 'sktype': 'Passive' },
	{'skname': 'Magic Skill Up', 'sktype': 'Passive' },
];

